// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/generalzy/zeropan/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware.Handle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/create",
					Handler: CreateUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/user/retrieve",
				Handler: RetrieveUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/user/login",
				Handler: UserLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/score/save",
				Handler: SaveUserScoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/socre/callback",
				Handler: SaveUserScoreCallbackHandler(serverCtx),
			},
		},
	)
}
