// Code generated by goctl. DO NOT EDIT.
package types

type RetrieveUserRequest struct {
	ID string `json:"id"`
}

type RetrieveUserResponse struct {
	Name      string `bson:"name" json:"name"`
	Password  string `bson:"password" json:"password"`
	Email     string `bson:"email" json:"email"`
	CreatedAt string `bson:"created_at" json:"createdAt"`
	UpdatedAt string `bson:"updated_at" json:"updatedAt"`
	DeletedAt string `bson:"deleted_at" json:"deletedAt"`
}

type CreateUserRequest struct {
	Name     string `bson:"name" json:"name"`
	Password string `bson:"password" json:"password"`
	Email    string `bson:"email" json:"email""`
}

type CreateUserResponse struct {
	ID        string `json:"id"`
	Name      string `bson:"name" json:"name"`
	Email     string `bson:"email" json:"email"`
	CreatedAt string `bson:"created_at" json:"createdAt"`
	UpdatedAt string `bson:"updated_at" json:"updatedAt"`
}

type UserLoginRequest struct {
	Name     string `bson:"name" json:"name"`
	Password string `bson:"password" json:"password"`
}

type UserLoginResponse struct {
	Token string `bson:"token"`
}

type UserScoreRequest struct {
	ID    string `json:"id"`
	Score int32  `json:"score"`
}

type UserScoreResponse struct {
	ID    string `json:"id"`
	Score int32  `json:"score"`
}
